# Generated by Django 3.1.7 on 2021-03-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
