# Generated by Django 3.1.7 on 2021-04-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='User_name',
            field=models.CharField(max_length=200),
        ),
    ]
