# Generated by Django 3.1.7 on 2021-04-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210401_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
